linters:
  disable:
    - exhaustivestruct
    - tagliatelle
    - exhaustruct
    - nosnakecase
    - godox
    - musttag
    - gci
    - ifshort

  enable-all: true

linters-settings:
  revive:
    checks:
      - all
      - unused-parameter