linters:
  disable:
    - exhaustivestruct
    - tagliatelle
    - exhaustruct
    - nosnakecase
    - godox
    - musttag
    - gci
    - ifshort

  enable-all: true

issues:
  exclude:
    - unused-parameter